### ISSUE TITLE
How does this work without the gatsby-plugin-material-ui?

### ISSUE THREAD

**Issue by kompounder** [WebCu/gatsby-material-kit-react#12]
Thank you for this. I was wondering what the difference is between an implementation that uses the gatsby-plugin-material-ui vs. an implementation that doesn't. Thank you!

**Comment by lannonbr** [comment]
Hey @WebCu and @kompounder, so I've seen this issue twice this week in the Gatsby core repo with several people running into this and I wanted to give some context and a solution to this issue.

So for context, by default material-ui does not have SSR baked in, although using the plugin @kompounder mentioned, [`gatsby-plugin-material-ui`](https://www.gatsbyjs.org/packages/gatsby-plugin-material-ui/?=material), you can make it so it does do SSR at build time.

That said, given this starter is still based on v3 of Material UI, you have to pin the version of `gatsby-plugin-material-ui` to 1.2.5, which was the last version to support Material UI v3.

@WebCu, I could push a PR that includes this fix if that is alright with you.

**Comment by WebCu** [comment]
Thanks @kompounder for the question and @lannonbr for the response :) your PR of course is welcome! I haven't been able to find the time to keep update this project but I'll try improve in the future.
