### ISSUE TITLE
Initial load distorted

### ISSUE THREAD

**Issue by ptrobert** [WebCu/gatsby-material-kit-react#13]
On initial Load distortion is happening
Steps to reproduce, deploy the app to netlify and open it in chrome incognito window (to avoid cache) , Please see the screen shot for distortion

![Screenshot from 2019-05-28 00-59-50](https://user-images.githubusercontent.com/22412467/58436614-e33f0380-80e3-11e9-96b6-1fcb89f68525.png)

**Comment by ptrobert** [comment]
Hi added gatsby material ui plugin and this distortion is gone,  use version 1.2.4

**Comment by WebCu** [comment]
Thanks @ptrobert for report this! I just merged a MR from @lannonbr that solve this issue.
